# Generated by Django 4.1.6 on 2023-02-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
